version: 2.1


executors:
  node-latest:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest

jobs:
  init:
    executor: node-latest
    steps:
      - checkout
      - run:
          name: install ci tools
          command: 'mkdir -p ~/.build_tools/node && npm install --prefix ~/.build_tools/node kl-ci-tools'
      - run:
          name: update dependencies if releasing
          command: |
            if [[ "$CIRCLE_BRANCH" =~ release/v.* ]]; then
              ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js deps | xargs -I[] npm install []@latest
            fi
      - run:
          name: npm install
          command: npm i
      - run:
          name: npm build
          command: npm run build
      - save_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
          paths:
            - dist
            - package.json
            - node_modules
            - ~/.build_tools

  test:
    executor: node-latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: lint
          command: npm run lint

  publish-dev:
    executor: node-latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: set develop version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js tag dev.[]
      - run:
          name: authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: publish package
          command: npm publish --tag develop

  publish-latest:
    executor: node-latest
    steps:
      - checkout
      - restore_cache:
          key: git-sha-{{ .Revision }}{{ .Branch }}
      - run:
          name: setup git config
          command: git config user.email "dev@mazzaroth.io" && git config user.name "CircleCI" && git config --global core.editor "\usr\local\bin\subl -n -w"
      - run:
          name: update version
          command: echo $CIRCLE_BRANCH | sed 's:release/::' | xargs npm version --no-git-tag-version
      - run:
          name: verify package.json
          command: ~/.build_tools/node/node_modules/kl-ci-tools/dist/bin.js validate
      - run:
          name: commit updates
          command: git add -A && git commit -m "Dependency/Version update for $CIRCLE_BRANCH"
      - run:
          name: update master
          command: git rebase -Xtheirs origin/master && git push origin $CIRCLE_BRANCH:master
      - run:
          name: authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: tag release
          command: |
            env GIT_TAG=$(echo $CIRCLE_BRANCH | sed 's:release/::')
            git checkout master
            git tag $GIT_TAG
            git push origin $GIT_TAG
      - run:
          name: publish package
          command: npm publish --tag latest
      - run:
          name: checkout and develop
          command: git checkout develop
      - run:
          name: update develop version
          command: echo $CIRCLE_BRANCH | sed 's:release/::' | xargs npm --no-git-tag-version version
      - run:
          name: commit updates
          command: git add -A && git commit -m "Version update for $CIRCLE_BRANCH" && git push origin develop

workflows:
  version: 2.1
  build_test_release:
    jobs:
      - init
      - test:
          requires:
            - init
      - publish-dev:
          requires:
            - test
          filters:
            branches:
              only: develop
      - publish-latest:
          requires:
            - test
          filters:
            branches:
              only: /release\/v([0-9]+)\.([0-9]+)\.([0-9]+)$/
