version: 0.0.1
type: deployment 
channel:
  version: 0.0.1
  id: 00000000000000000000000000000000
  owner: 00000000000000000000000000000000
  contract-file: "samplecontract.wasm"
  abi-file: "samplecontract.json"
gateway-node:
  address: https://localhost:8081 
transactions:
  - tx: 
      function: "init" 
      args: ["1","2","3","4"]
  - tx: 
      function: "balanceof" 
      args: ["1","2","3","4"]

